# Generated by Django 3.1.4 on 2021-04-29 07:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular equipment', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('total_quantity', models.IntegerField(null=True)),
                ('available_quantity', models.IntegerField(null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.clubs')),
            ],
        ),
    ]
