# Generated by Django 3.1.7 on 2021-05-02 12:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular equipment', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('total_quantity', models.IntegerField(null=True)),
                ('available_quantity', models.IntegerField(null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportapp.clubs')),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_return', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('req', models.BooleanField(default=False)),
                ('equipment_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportapp.equipment')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
