# Generated by Django 3.1.4 on 2021-04-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_return', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('equipment_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sportapp.equipment')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
