# Generated by Django 3.1.5 on 2021-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0002_equipment_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
