# Generated by Django 3.1.4 on 2021-04-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0003_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='equipment_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportapp.equipment'),
        ),
    ]
