# Generated by Django 3.1.5 on 2021-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0004_equipment_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='generalequipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('total_quantity', models.IntegerField(null=True)),
                ('available_quantity', models.IntegerField(null=True)),
                ('specification', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='clubs',
            name='dept',
            field=models.CharField(default=1, help_text='Department', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubs',
            name='prog',
            field=models.CharField(default=1, help_text='Programme', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
