# Generated by Django 3.1.5 on 2021-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0006_auto_20210507_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='remark',
            field=models.TextField(default=None, null=True),
        ),
    ]
