# Generated by Django 3.1.4 on 2021-05-10 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0007_auto_20210507_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_gen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportapp.clubs'),
        ),
    ]
