# Generated by Django 3.2.4 on 2021-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0008_auto_20210510_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='generalequipment',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='generalequipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
